trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

parameters:
- name: initSteps
  type: stepList
  default:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: yarn
      displayName: "Install npm dependencies"

    - script: |
        python -m pip install --upgrade --upgrade-strategy=eager pip
        pip install --upgrade --upgrade-strategy=eager -e .[dev]
      displayName: 'Install Python dependencies'

    - script: |
        which python > python.txt
        set /p PYTHON=<python.txt
        ln -s %PYTHON% %PYTHON%$(python.version)
        python --version
        which python$(python.version)
      displayName: "Which python"

    - bash: env
      displayName: "List all environment variables"

- name: initDockerSteps
  type: stepList
  default:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: 19.03.8
        releaseType: stable
      displayName: 'Setup docker'

- name: initDockerStepsMac
  type: stepList
  default:
    - script: |
        ci/install_docker_desktop_mac.sh
        ci/start_docker_desktop_mac.sh
      displayName: 'Setup docker desktop for mac'

- name: pullContainersSteps
  type: stepList
  default:
    - script: |
        docker pull andrewgaul/s3proxy
        docker pull dperson/samba
      displayName: 'Pull containers used by tests'

- name: initS3proxyStepsLocal
  type: stepList
  default:
    - bash: |
        nohup ci/s3_local.sh -d -r
        sleep 5
      displayName: "Start up local S3 server"

    - script: curl http://127.0.0.1:9000/
      displayName: 'Test local S3 server'

- name: initSmbOsWindows
  type: stepList
  default:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'ci/enable_os_share_windows.ps1'
        errorActionPreference: 'stop'
        failOnStderr: True
      displayName: 'Enable os builtin file sharing'
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'ci/create_os_share_windows.ps1'
        errorActionPreference: 'stop'
        failOnStderr: True
      displayName: 'Create share on os builtin samba server'

- name: testSteps
  type: stepList
  default:
    - script: make lintpy
      displayName: 'Lint Python'

    - script: make lintjs
      displayName: 'Lint JS'

    - script: make testpy
      displayName: 'Test Python'

    - script: make testjs
      displayName: 'Test JS'

- name: publishSteps
  type: stepList
  default:
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - ${{ parameters.initDockerSteps }}
    - ${{ parameters.pullContainersSteps }}
    - ${{ parameters.initSteps }}
    - ${{ parameters.testSteps }}
    - ${{ parameters.publishSteps }}

- job: 'Mac'
  pool:
    vmImage: 'macos-10.14'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - ${{ parameters.initDockerStepsMac }}
    - ${{ parameters.pullContainersSteps }}
    - ${{ parameters.initSteps }}
    - ${{ parameters.testSteps }}
    - ${{ parameters.publishSteps }}

# - job: 'Windows'
#   pool:
#     vmImage: 'windows-2019'

#   strategy:
#     matrix:
#       Python37:
#         python.version: '3.7'

#   steps:
#     - ${{ parameters.initSmbOsWindows }}
#     - ${{ parameters.initS3proxyStepsLocal }}
#     - ${{ parameters.initSteps }}
#     - ${{ parameters.testSteps }}
#     - ${{ parameters.publishSteps }}
